modLoader="javafml"
loaderVersion="[36,)"
logoFile="HellasControl.png"
license="Restricted"

[[mods]]
modId="hellascontrol"
version="1.0.0"
displayName="HellasControl"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
'''

[[dependencies.hellascontrol]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellascontrol]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellascontrol]]
modId="pixelmon"
mandatory=true
versionRange="[9.1.12,)"
ordering="AFTER"
side="BOTH"